### ISSUE TITLE
Unable to Debug Durable Entities on local machine

### ISSUE THREAD

**Issue by harrict** [microsoft/durabletask-netherite#361]
I'm trying to use Netherite with a durable function that also utilizes durable entities. The function app is a .NET 8 isolated function. I am trying to ensure the functionality works before publishing to Azure but when I test locally I get an error when calling any of the durable entity methods. When calling either SignalEntityAsync or CallEntityAsync I get an NullReferenceException at DurableTask.Core.Entities.OrchestrationEntityContext.AdjustOutgoingMessage. The null reference seems to be for this.innerContext.EntityParameters.EntityMessageReorderWindow.

More details:
- I tested the function not using Netherite, just using Azure Storage, and it works fine
- I've tried both Memory and SingleHost emulation modes as well as pointing directly to an event hub resource but still get the same error
- The entity is a basic counter entity that is a copy of the example on microsoft's site

**Comment by sebastianburckhardt** [comment]
Sorry about this. In fact, this behavior is consistent with known bugs / limitations. 

There are two problems here currently:

- Support for isolated entities on Netherite has not yet been released (the PR is done, see #358, but we are currently waiting for the next release of DF Extension before we can release it).
- The error `NullReferenceException` is not an acceptable error message since it does not describe the issue. We have fixed this error message (see https://github.com/Azure/durabletask/pull/989) but that fix has also not yet been released.

**Comment by jaliyaudagedara** [comment]
Still getting `System.NotSupportedException: Durable entities are not supported by the current backend configuration` with `1.5.1`.

Logged an issue: https://github.com/microsoft/durabletask-netherite/issues/390
